### ISSUE TITLE
Region specific settings (cacheTimeSeconds) are not applied

### ISSUE THREAD

**Issue by yvesf** [mihaicostin/hibernate-l2-memcached#1]
The `MemcachedCache` class which represents a region doesn't read the region specific configuration.

For example, if you configure (yaml syntax):

```
hibernate:
    cache:
        memcached:
            operationTimeout: 700 #700ms
            # Specific per region
            com.bla.product.ClassName.cacheTimeSeconds: 300 # 5min
```

Then operationTimeout will be applied as intended but the cacheTimeSeconds for the "com.bla.product.ClassName" region is not applied.
